"""initial sqlite schema

SQLite 기준 baseline 스키마.

기존 MySQL 스키마와의 연속성을 갖는 마이그레이션이 아니다.
레거시 MySQL 데이터는 scripts/migrate_mysql_to_sqlite.py 가 별도로 이전한다.
설계 근거: docs/refactoring/database/01-target-sqlite-schema.md

Revision ID: 0001
Revises:
Create Date: 2026-07-31

"""
from alembic import op
import sqlalchemy as sa

import db_types


# revision identifiers, used by Alembic.
revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('common_bills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('billing_month', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('total_amount', db_types.Money(), server_default=sa.text('0'), nullable=False),
    sa.Column('distribution_method', sa.String(length=20), server_default='BY_RESIDENTS', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("distribution_method IN ('BY_RESIDENTS', 'BY_UNITS')", name=op.f('ck_common_bills_distribution_method_valid')),
    sa.CheckConstraint("substr(billing_month, 9, 2) = '01'", name=op.f('ck_common_bills_billing_month_first_day')),
    sa.CheckConstraint('total_amount >= 0', name=op.f('ck_common_bills_total_amount_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_common_bills'))
    )
    with op.batch_alter_table('common_bills', schema=None) as batch_op:
        batch_op.create_index('ix_common_bills_billing_month', ['billing_month'], unique=False)

    op.create_table('floors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('floor_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('electric_contract_number', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_floors')),
    sa.UniqueConstraint('floor_number', name=op.f('uq_floors_floor_number'))
    )
    op.create_table('invoice_combinations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_name', sa.String(length=255), nullable=False),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoice_combinations'))
    )
    with op.batch_alter_table('invoice_combinations', schema=None) as batch_op:
        batch_op.create_index('ix_invoice_combinations_created_at', ['created_at'], unique=False)

    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('setting_key', sa.String(length=50), nullable=False),
    sa.Column('setting_value', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_settings')),
    sa.UniqueConstraint('setting_key', name=op.f('uq_settings_setting_key'))
    )
    op.create_table('water_bills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('billing_month', sa.Date(), nullable=False),
    sa.Column('total_amount', db_types.Money(), server_default=sa.text('0'), nullable=False),
    sa.Column('welfare_discount_total', db_types.Money(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("substr(billing_month, 9, 2) = '01'", name=op.f('ck_water_bills_billing_month_first_day')),
    sa.CheckConstraint('total_amount >= 0', name=op.f('ck_water_bills_total_amount_non_negative')),
    sa.CheckConstraint('welfare_discount_total >= 0', name=op.f('ck_water_bills_welfare_discount_total_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_water_bills')),
    sa.UniqueConstraint('billing_month', name=op.f('uq_water_bills_billing_month'))
    )
    op.create_table('electric_bills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('billing_month', sa.Date(), nullable=False),
    sa.Column('floor_id', sa.Integer(), nullable=False),
    sa.Column('total_amount', db_types.Money(), server_default=sa.text('0'), nullable=False),
    sa.Column('welfare_discount', db_types.Money(), server_default=sa.text('0'), nullable=False),
    sa.Column('voucher_discount', db_types.Money(), server_default=sa.text('0'), nullable=False),
    sa.Column('tv_fee_total', db_types.Money(), server_default=sa.text('0'), nullable=False),
    sa.Column('tv_distribution_mode', sa.String(length=20), server_default='INDIVIDUAL', nullable=False),
    sa.Column('billing_months_count', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("substr(billing_month, 9, 2) = '01'", name=op.f('ck_electric_bills_billing_month_first_day')),
    sa.CheckConstraint("tv_distribution_mode IN ('INDIVIDUAL', 'EQUAL')", name=op.f('ck_electric_bills_tv_distribution_mode_valid')),
    sa.CheckConstraint('billing_months_count >= 0', name=op.f('ck_electric_bills_billing_months_count_non_negative')),
    sa.CheckConstraint('total_amount >= 0', name=op.f('ck_electric_bills_total_amount_non_negative')),
    sa.CheckConstraint('tv_fee_total >= 0', name=op.f('ck_electric_bills_tv_fee_total_non_negative')),
    sa.CheckConstraint('voucher_discount >= 0', name=op.f('ck_electric_bills_voucher_discount_non_negative')),
    sa.CheckConstraint('welfare_discount >= 0', name=op.f('ck_electric_bills_welfare_discount_non_negative')),
    sa.ForeignKeyConstraint(['floor_id'], ['floors.id'], name=op.f('fk_electric_bills_floor_id_floors'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_electric_bills')),
    sa.UniqueConstraint('floor_id', 'billing_month', name='uq_electric_bills_floor_id_billing_month')
    )
    with op.batch_alter_table('electric_bills', schema=None) as batch_op:
        batch_op.create_index('ix_electric_bills_billing_month', ['billing_month'], unique=False)

    op.create_table('units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('floor_id', sa.Integer(), nullable=False),
    sa.Column('unit_name', sa.String(length=50), nullable=False),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('electric_welfare', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('electric_voucher', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('has_tv', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('water_welfare', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('residents_count', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('is_vacant', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('residents_count >= 0', name=op.f('ck_units_residents_count_non_negative')),
    sa.ForeignKeyConstraint(['floor_id'], ['floors.id'], name=op.f('fk_units_floor_id_floors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_units')),
    sa.UniqueConstraint('floor_id', 'unit_name', name='uq_units_floor_id_unit_name')
    )
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.create_index('ix_units_floor_id', ['floor_id'], unique=False)

    op.create_table('common_bill_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('common_bill_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('amount', db_types.ExactDecimal(), nullable=False),
    sa.Column('charged_amount', db_types.Money(), nullable=False),
    sa.Column('unit_snapshot', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('CAST(amount AS REAL) >= 0', name=op.f('ck_common_bill_details_amount_non_negative')),
    sa.CheckConstraint('charged_amount >= 0', name=op.f('ck_common_bill_details_charged_amount_non_negative')),
    sa.ForeignKeyConstraint(['common_bill_id'], ['common_bills.id'], name=op.f('fk_common_bill_details_common_bill_id_common_bills'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], name=op.f('fk_common_bill_details_unit_id_units'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_common_bill_details')),
    sa.UniqueConstraint('common_bill_id', 'unit_id', name='uq_common_bill_details_common_bill_id_unit_id')
    )
    with op.batch_alter_table('common_bill_details', schema=None) as batch_op:
        batch_op.create_index('ix_common_bill_details_unit_id', ['unit_id'], unique=False)

    op.create_table('electric_bill_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('electric_bill_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('usage_amount', db_types.ExactDecimal(), nullable=False),
    sa.Column('base_amount', db_types.ExactDecimal(), nullable=False),
    sa.Column('welfare_discount', db_types.ExactDecimal(), server_default='0.00', nullable=False),
    sa.Column('voucher_discount', db_types.ExactDecimal(), server_default='0.00', nullable=False),
    sa.Column('tv_fee', db_types.ExactDecimal(), server_default='0.00', nullable=False),
    sa.Column('final_amount', db_types.ExactDecimal(), nullable=False),
    sa.Column('charged_amount', db_types.Money(), nullable=False),
    sa.Column('unit_snapshot', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('CAST(final_amount AS REAL) >= 0', name=op.f('ck_electric_bill_details_final_amount_non_negative')),
    sa.CheckConstraint('CAST(tv_fee AS REAL) >= 0', name=op.f('ck_electric_bill_details_tv_fee_non_negative')),
    sa.CheckConstraint('CAST(voucher_discount AS REAL) >= 0', name=op.f('ck_electric_bill_details_voucher_discount_non_negative')),
    sa.CheckConstraint('CAST(welfare_discount AS REAL) >= 0', name=op.f('ck_electric_bill_details_welfare_discount_non_negative')),
    sa.CheckConstraint('charged_amount >= 0', name=op.f('ck_electric_bill_details_charged_amount_non_negative')),
    sa.ForeignKeyConstraint(['electric_bill_id'], ['electric_bills.id'], name=op.f('fk_electric_bill_details_electric_bill_id_electric_bills'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], name=op.f('fk_electric_bill_details_unit_id_units'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_electric_bill_details')),
    sa.UniqueConstraint('electric_bill_id', 'unit_id', name='uq_electric_bill_details_electric_bill_id_unit_id')
    )
    with op.batch_alter_table('electric_bill_details', schema=None) as batch_op:
        batch_op.create_index('ix_electric_bill_details_unit_id', ['unit_id'], unique=False)

    op.create_table('electric_bill_months',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('electric_bill_id', sa.Integer(), nullable=False),
    sa.Column('billing_month', sa.Date(), nullable=False),
    sa.Column('amount', db_types.Money(), server_default=sa.text('0'), nullable=False),
    sa.Column('welfare_discount', db_types.Money(), server_default=sa.text('0'), nullable=False),
    sa.Column('voucher_discount', db_types.Money(), server_default=sa.text('0'), nullable=False),
    sa.Column('tv_fee', db_types.Money(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("substr(billing_month, 9, 2) = '01'", name=op.f('ck_electric_bill_months_billing_month_first_day')),
    sa.CheckConstraint('amount >= 0', name=op.f('ck_electric_bill_months_amount_non_negative')),
    sa.CheckConstraint('tv_fee >= 0', name=op.f('ck_electric_bill_months_tv_fee_non_negative')),
    sa.CheckConstraint('voucher_discount >= 0', name=op.f('ck_electric_bill_months_voucher_discount_non_negative')),
    sa.CheckConstraint('welfare_discount >= 0', name=op.f('ck_electric_bill_months_welfare_discount_non_negative')),
    sa.ForeignKeyConstraint(['electric_bill_id'], ['electric_bills.id'], name=op.f('fk_electric_bill_months_electric_bill_id_electric_bills'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_electric_bill_months')),
    sa.UniqueConstraint('electric_bill_id', 'billing_month', name='uq_electric_bill_months_electric_bill_id_billing_month')
    )
    with op.batch_alter_table('electric_bill_months', schema=None) as batch_op:
        batch_op.create_index('ix_electric_bill_months_billing_month', ['billing_month'], unique=False)

    op.create_table('electric_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('electric_bill_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('previous_reading', db_types.ExactDecimal(), nullable=False),
    sa.Column('current_reading', db_types.ExactDecimal(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('CAST(current_reading AS REAL) >= 0', name=op.f('ck_electric_readings_current_reading_non_negative')),
    sa.CheckConstraint('CAST(previous_reading AS REAL) >= 0', name=op.f('ck_electric_readings_previous_reading_non_negative')),
    sa.ForeignKeyConstraint(['electric_bill_id'], ['electric_bills.id'], name=op.f('fk_electric_readings_electric_bill_id_electric_bills'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], name=op.f('fk_electric_readings_unit_id_units'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_electric_readings')),
    sa.UniqueConstraint('electric_bill_id', 'unit_id', name='uq_electric_readings_electric_bill_id_unit_id')
    )
    with op.batch_alter_table('electric_readings', schema=None) as batch_op:
        batch_op.create_index('ix_electric_readings_unit_id', ['unit_id'], unique=False)

    op.create_table('final_invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('combination_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('electric_amount', db_types.Money(), server_default=sa.text('0'), nullable=False),
    sa.Column('water_amount', db_types.Money(), server_default=sa.text('0'), nullable=False),
    sa.Column('common_amount', db_types.Money(), server_default=sa.text('0'), nullable=False),
    sa.Column('common_details', sa.JSON(), nullable=True),
    sa.Column('total_amount', db_types.Money(), nullable=False),
    sa.Column('unit_memo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('common_amount >= 0', name=op.f('ck_final_invoices_common_amount_non_negative')),
    sa.CheckConstraint('electric_amount >= 0', name=op.f('ck_final_invoices_electric_amount_non_negative')),
    sa.CheckConstraint('water_amount >= 0', name=op.f('ck_final_invoices_water_amount_non_negative')),
    sa.ForeignKeyConstraint(['combination_id'], ['invoice_combinations.id'], name=op.f('fk_final_invoices_combination_id_invoice_combinations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], name=op.f('fk_final_invoices_unit_id_units'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_final_invoices')),
    sa.UniqueConstraint('combination_id', 'unit_id', name='uq_final_invoices_combination_id_unit_id')
    )
    with op.batch_alter_table('final_invoices', schema=None) as batch_op:
        batch_op.create_index('ix_final_invoices_unit_id', ['unit_id'], unique=False)

    op.create_table('invoice_combination_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('combination_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(length=20), nullable=False),
    sa.Column('billing_month', sa.Date(), nullable=False),
    sa.Column('item_description', sa.String(length=200), nullable=True),
    sa.Column('electric_bill_id', sa.Integer(), nullable=True),
    sa.Column('water_bill_id', sa.Integer(), nullable=True),
    sa.Column('common_bill_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("( (item_type = 'ELECTRIC' AND electric_bill_id IS NOT NULL   AND water_bill_id IS NULL AND common_bill_id IS NULL) OR (item_type = 'WATER' AND water_bill_id IS NOT NULL   AND electric_bill_id IS NULL AND common_bill_id IS NULL) OR (item_type = 'COMMON' AND common_bill_id IS NOT NULL   AND electric_bill_id IS NULL AND water_bill_id IS NULL))", name=op.f('ck_invoice_combination_items_exactly_one_bill_reference')),
    sa.CheckConstraint("item_type IN ('ELECTRIC', 'WATER', 'COMMON')", name=op.f('ck_invoice_combination_items_item_type_valid')),
    sa.CheckConstraint("substr(billing_month, 9, 2) = '01'", name=op.f('ck_invoice_combination_items_billing_month_first_day')),
    sa.ForeignKeyConstraint(['combination_id'], ['invoice_combinations.id'], name=op.f('fk_invoice_combination_items_combination_id_invoice_combinations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['common_bill_id'], ['common_bills.id'], name=op.f('fk_invoice_combination_items_common_bill_id_common_bills'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['electric_bill_id'], ['electric_bills.id'], name=op.f('fk_invoice_combination_items_electric_bill_id_electric_bills'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['water_bill_id'], ['water_bills.id'], name=op.f('fk_invoice_combination_items_water_bill_id_water_bills'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoice_combination_items'))
    )
    with op.batch_alter_table('invoice_combination_items', schema=None) as batch_op:
        batch_op.create_index('ix_invoice_combination_items_combination_id', ['combination_id'], unique=False)
        batch_op.create_index('ix_invoice_combination_items_common_bill_id', ['common_bill_id'], unique=False)
        batch_op.create_index('ix_invoice_combination_items_electric_bill_id', ['electric_bill_id'], unique=False)
        batch_op.create_index('ix_invoice_combination_items_water_bill_id', ['water_bill_id'], unique=False)

    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('combination_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('payment_amount', db_types.Money(), nullable=False),
    sa.Column('payment_method', sa.String(length=50), server_default='계좌이체', nullable=False),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('payment_amount >= 0', name=op.f('ck_payments_payment_amount_non_negative')),
    sa.ForeignKeyConstraint(['combination_id'], ['invoice_combinations.id'], name=op.f('fk_payments_combination_id_invoice_combinations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], name=op.f('fk_payments_unit_id_units'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments'))
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index('ix_payments_combination_id', ['combination_id'], unique=False)
        batch_op.create_index('ix_payments_payment_date', ['payment_date'], unique=False)
        batch_op.create_index('ix_payments_unit_id', ['unit_id'], unique=False)

    op.create_table('water_bill_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('water_bill_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('base_amount', db_types.ExactDecimal(), nullable=False),
    sa.Column('welfare_discount', db_types.ExactDecimal(), server_default='0.00', nullable=False),
    sa.Column('final_amount', db_types.ExactDecimal(), nullable=False),
    sa.Column('charged_amount', db_types.Money(), nullable=False),
    sa.Column('unit_snapshot', sa.JSON(), nullable=True),
    sa.Column('is_excluded', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('CAST(base_amount AS REAL) >= 0', name=op.f('ck_water_bill_details_base_amount_non_negative')),
    sa.CheckConstraint('CAST(final_amount AS REAL) >= 0', name=op.f('ck_water_bill_details_final_amount_non_negative')),
    sa.CheckConstraint('CAST(welfare_discount AS REAL) >= 0', name=op.f('ck_water_bill_details_welfare_discount_non_negative')),
    sa.CheckConstraint('charged_amount >= 0', name=op.f('ck_water_bill_details_charged_amount_non_negative')),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], name=op.f('fk_water_bill_details_unit_id_units'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['water_bill_id'], ['water_bills.id'], name=op.f('fk_water_bill_details_water_bill_id_water_bills'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_water_bill_details')),
    sa.UniqueConstraint('water_bill_id', 'unit_id', name='uq_water_bill_details_water_bill_id_unit_id')
    )
    with op.batch_alter_table('water_bill_details', schema=None) as batch_op:
        batch_op.create_index('ix_water_bill_details_unit_id', ['unit_id'], unique=False)

    op.create_table('final_invoice_charges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('final_invoice_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('amount', db_types.Money(), nullable=False),
    sa.Column('is_carryover', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['final_invoice_id'], ['final_invoices.id'], name=op.f('fk_final_invoice_charges_final_invoice_id_final_invoices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_final_invoice_charges'))
    )
    with op.batch_alter_table('final_invoice_charges', schema=None) as batch_op:
        batch_op.create_index('ix_final_invoice_charges_final_invoice_id', ['final_invoice_id'], unique=False)
        batch_op.create_index('ix_final_invoice_charges_is_carryover', ['is_carryover'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('final_invoice_charges', schema=None) as batch_op:
        batch_op.drop_index('ix_final_invoice_charges_is_carryover')
        batch_op.drop_index('ix_final_invoice_charges_final_invoice_id')

    op.drop_table('final_invoice_charges')
    with op.batch_alter_table('water_bill_details', schema=None) as batch_op:
        batch_op.drop_index('ix_water_bill_details_unit_id')

    op.drop_table('water_bill_details')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index('ix_payments_unit_id')
        batch_op.drop_index('ix_payments_payment_date')
        batch_op.drop_index('ix_payments_combination_id')

    op.drop_table('payments')
    with op.batch_alter_table('invoice_combination_items', schema=None) as batch_op:
        batch_op.drop_index('ix_invoice_combination_items_water_bill_id')
        batch_op.drop_index('ix_invoice_combination_items_electric_bill_id')
        batch_op.drop_index('ix_invoice_combination_items_common_bill_id')
        batch_op.drop_index('ix_invoice_combination_items_combination_id')

    op.drop_table('invoice_combination_items')
    with op.batch_alter_table('final_invoices', schema=None) as batch_op:
        batch_op.drop_index('ix_final_invoices_unit_id')

    op.drop_table('final_invoices')
    with op.batch_alter_table('electric_readings', schema=None) as batch_op:
        batch_op.drop_index('ix_electric_readings_unit_id')

    op.drop_table('electric_readings')
    with op.batch_alter_table('electric_bill_months', schema=None) as batch_op:
        batch_op.drop_index('ix_electric_bill_months_billing_month')

    op.drop_table('electric_bill_months')
    with op.batch_alter_table('electric_bill_details', schema=None) as batch_op:
        batch_op.drop_index('ix_electric_bill_details_unit_id')

    op.drop_table('electric_bill_details')
    with op.batch_alter_table('common_bill_details', schema=None) as batch_op:
        batch_op.drop_index('ix_common_bill_details_unit_id')

    op.drop_table('common_bill_details')
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.drop_index('ix_units_floor_id')

    op.drop_table('units')
    with op.batch_alter_table('electric_bills', schema=None) as batch_op:
        batch_op.drop_index('ix_electric_bills_billing_month')

    op.drop_table('electric_bills')
    op.drop_table('water_bills')
    op.drop_table('settings')
    with op.batch_alter_table('invoice_combinations', schema=None) as batch_op:
        batch_op.drop_index('ix_invoice_combinations_created_at')

    op.drop_table('invoice_combinations')
    op.drop_table('floors')
    with op.batch_alter_table('common_bills', schema=None) as batch_op:
        batch_op.drop_index('ix_common_bills_billing_month')

    op.drop_table('common_bills')
    # ### end Alembic commands ###
